apiVersion: v1
name: bitcoin-controller-helm-qa
version: 0.63-devc744501
description: A bitcoin controller for Kubernetes
appVersion: c744501
maintainers:
  - name: christianb93
    url: https://www.github.com/christianb93/bitcoin-controller
