apiVersion: v1
name: bitcoin-controller-helm-qa
version: 0.8-dev13220cf
description: A bitcoin controller for Kubernetes
appVersion: 13220cf
maintainers:
  - name: christianb93
    url: https://www.github.com/christianb93/bitcoin-controller
