apiVersion: v1
name: bitcoin-controller-helm-qa
version: 0.63-devc4c7e2d
description: A bitcoin controller for Kubernetes
appVersion: c4c7e2d
maintainers:
  - name: christianb93
    url: https://www.github.com/christianb93/bitcoin-controller
