apiVersion: v1
name: bitcoin-controller-helm-qa
version: 0.63-dev78e4683
description: A bitcoin controller for Kubernetes
appVersion: 78e4683
maintainers:
  - name: christianb93
    url: https://www.github.com/christianb93/bitcoin-controller
