apiVersion: v1
kind: Pod
metadata:
  name: bitcoin-controller
  namespace: bitcoin-controller
spec:
  serviceAccountName: bitcoin-controller-sva
  containers:
  - name: bitcoin-controller-ctr
    image: christianb93/bitcoin-controller:{{.Values.controller_image_tag}}
